version: "3.6"
services:
  discovery:
    build: ./EurekaServer
    ports:
      - "8756:8755"
    image: "eureka-service"

  stage:
    build: ./StagiaireMSA
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3002:8082"
    image: "stage-service"
    depends_on:
      - discovery

  gateway:
    build: ./API-Gateway_Server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3006:8090"
    image: "gateway-service"
    depends_on:
      - discovery

